"""Proposal model — executable action proposal.

Proposals are generated from planning recommendations.
They require explicit user approval before any external execution.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone, timedelta
from enum import StrEnum
from typing import Any
from uuid import UUID, uuid4


class ProposalType(StrEnum):
    CREATE_CALENDAR_BLOCK = "create_calendar_block"
    UPDATE_CALENDAR_EVENT = "update_calendar_event"
    DELETE_CALENDAR_EVENT = "delete_calendar_event"
    SCHEDULE_REMINDER = "schedule_reminder"
    MOVE_TASK = "move_low_priority_task"


class ProposalStatus(StrEnum):
    PENDING = "pending"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    EXPIRED = "expired"


class TargetSystem(StrEnum):
    GOOGLE_CALENDAR = "google_calendar"
    TELEGRAM_REMINDER = "telegram_reminder"


@dataclass
class Proposal:
    """Immutable proposal for an external action.

    Generated by the system, requires user approval to execute.
    """
    proposal_id: str = field(default_factory=lambda: uuid4().hex[:12])
    proposal_type: ProposalType = ProposalType.CREATE_CALENDAR_BLOCK
    target_system: TargetSystem = TargetSystem.GOOGLE_CALENDAR
    action_payload: dict[str, Any] = field(default_factory=dict)
    reason: str = ""
    confidence: float = 0.5
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    expires_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc) + timedelta(hours=1))
    status: ProposalStatus = ProposalStatus.PENDING
    user_id: str = ""

    def is_expired(self, now: datetime | None = None) -> bool:
        if now is None:
            now = datetime.now(timezone.utc)
        return now > self.expires_at

    def to_dict(self) -> dict[str, Any]:
        return {
            "proposal_id": self.proposal_id,
            "proposal_type": self.proposal_type.value,
            "target_system": self.target_system.value,
            "action_payload": self.action_payload,
            "reason": self.reason,
            "confidence": self.confidence,
            "created_at": self.created_at.isoformat(),
            "expires_at": self.expires_at.isoformat(),
            "status": self.status.value,
            "user_id": self.user_id,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Proposal:
        return cls(
            proposal_id=data.get("proposal_id", ""),
            proposal_type=ProposalType(data.get("proposal_type", "create_calendar_block")),
            target_system=TargetSystem(data.get("target_system", "google_calendar")),
            action_payload=data.get("action_payload", {}),
            reason=data.get("reason", ""),
            confidence=data.get("confidence", 0.5),
            created_at=datetime.fromisoformat(data["created_at"]) if data.get("created_at") else datetime.now(timezone.utc),
            expires_at=datetime.fromisoformat(data["expires_at"]) if data.get("expires_at") else datetime.now(timezone.utc) + timedelta(hours=1),
            status=ProposalStatus(data.get("status", "pending")),
            user_id=data.get("user_id", ""),
        )
